version: '3'

services:
  database:
    image: postgres
    container_name: database_concept_node
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=Dr@gon
      - POSTGRES_DB=concept_node
    volumes:
      - ./pg_data:/data/postgres
    networks:
      - backend_concept_node


  app:
    build: .
    container_name: concept_node
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
     - database
    depends_on:
     - database
    networks:
      - backend_concept_node

networks:
  backend_concept_node:
    driver: bridge
